UJMExoBundle:
    resource: "@UJMExoBundle/Resources/config/routing.yml"
    prefix:   /

WSRest:
    type:     rest
    resource: UJM\ExoBundle\Controller\WSRestController
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
