##
 # ExoOnLine
 # Copyright or © or Copr. Université Jean Monnet (France), 2012
 # dsi.dev@univ-st-etienne.fr
 #
 # This software is a computer program whose purpose is to [describe
 # functionalities and technical features of your software].
 #
 # This software is governed by the CeCILL license under French law and
 # abiding by the rules of distribution of free software.  You can  use,
 # modify and/ or redistribute the software under the terms of the CeCILL
 # license as circulated by CEA, CNRS and INRIA at the following URL
 # "http://www.cecill.info".
 #
 # As a counterpart to the access to the source code and  rights to copy,
 # modify and redistribute granted by the license, users are provided only
 # with a limited warranty  and the software's author,  the holder of the
 # economic rights,  and the successive licensors  have only  limited
 # liability.
 #
 # In this respect, the user's attention is drawn to the risks associated
 # with loading,  using,  modifying and/or developing or reproducing the
 # software by the user in light of its specific status of free software,
 # that may mean  that it is complicated to manipulate,  and  that  also
 # therefore means  that it is reserved for developers  and  experienced
 # professionals having in-depth computer knowledge. Users are therefore
 # encouraged to load and test the software's suitability as regards their
 # requirements in conditions enabling the security of their systems and/or
 # data to be ensured and,  more generally, to use and operate it in the
 # same conditions as regards security.
 #
 # The fact that you are presently reading this means that you have had
 # knowledge of the CeCILL license and that you accept its terms.
##

UJMExoBundle_homepage:
    pattern:  /hello/
    defaults: { _controller: UJMExoBundle:Default:index }

admin_Category:
    resource: "routing/admin/category.yml"
    prefix:   /admin/category

#admin_Choice:
#    resource: "routing/admin/choice.yml"
#    prefix:   /admin/choice

admin_exercise:
    resource: "routing/admin/exercise.yml"
    prefix:   /admin/exercise

admin_Hint:
    resource: "routing/admin/hint.yml"
    prefix:   /admin/hint

#admin_Interaction:
#    resource: "routing/admin/interaction.yml"
#    prefix:   /admin/interaction

admin_InteractionGraphic:
    resource: "routing/admin/interactionGraphic.yml"
    prefix:   /admin/interactiongraphic

admin_InteractionHole:
    resource: "routing/admin/interactionHole.yml"
    prefix:   /admin/interactionhole

admin_InteractionOpen:
    resource: "routing/admin/interactionOpen.yml"
    prefix:   /admin/interactionopen

admin_InteractionQCM:
    resource: "routing/admin/interactionQCM.yml"
    prefix:   /admin/interactionqcm

admin_paper:
    resource: "routing/admin/paper.yml"
    prefix:   /admin/paper

admin_Question:
    resource: "routing/admin/question.yml"
    prefix:   /admin/question

#admin_Response:
#    resource: "routing/admin/response.yml"
#    prefix:   /admin/response

admin_role:
    resource: "routing/admin/role.yml"
    prefix:   /admin/role

#admin_TypeQCM:
#    resource: "routing/admin/typeQCM.yml"
#    prefix:   /admin/typeqcm

admin_user:
    resource: "routing/admin/user.yml"
    prefix:   /admin/user
      
all_exercise:
    resource: "routing/all/exercise.yml"
    prefix:   /all/exercise

all_Hint:
    resource: "routing/all/hint.yml"
    prefix:   /all/hint

#all_Interaction:
#    resource: "routing/all/interaction.yml"
#    prefix:   /all/interaction

#all_InteractionGraphic:
#    resource: "routing/all/interactionGraphic.yml"
#    prefix:   /all/interactiongraphic

#all_InteractionHole:
#    resource: "routing/all/interactionHole.yml"
#    prefix:   /all/interactionhole

#all_InteractionOpen:
#    resource: "routing/all/interactionOpen.yml"
#    prefix:   /all/interactionopen

#all_InteractionQCM:
#    resource: "routing/all/interactionQCM.yml"
#    prefix:   /all/interactionqcm

all_login:
     resource: "routing/all/login.yml"
     prefix:   /all

all_paper:
    resource: "routing/all/paper.yml"
    prefix:   /all/paper